### PR TITLE
Signup changes

### PR DESCRIPTION
**Pull request by ShivaniMehendarge**
*Issue #, if available:*

*Description of changes:*
Removed the phone number field from signup form. After the changes, signup form contains only username, email and password. The verification code is sent via email.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by alexchirayath — APPROVED** [review]
LGTM

**Review by james-jory — CHANGES_REQUESTED** [review]
There is documentation that needs to be updated to reflect the new signup flow (instructions and screenshots). Here are two places I know for sure (may not be exhaustive--possible there are references in the workshops too).

https://github.com/aws-samples/retail-demo-store/blob/master/documentation/1-Creating-account.md

https://github.com/aws-samples/retail-demo-store/blob/master/workshop/Welcome.ipynb

**Comment by ShivaniMehendarge** [comment]
> There is documentation that needs to be updated to reflect the new signup flow (instructions and screenshots). Here are two places I know for sure (may not be exhaustive--possible there are references in the workshops too).
> 
> https://github.com/aws-samples/retail-demo-store/blob/master/documentation/1-Creating-account.md
> 
> https://github.com/aws-samples/retail-demo-store/blob/master/workshop/Welcome.ipynb

Made the changes in the above specified files and some other areas where I found the mention of signup and SMS.

**Review by alexchirayath — APPROVED** [review]
LGTM

**Review by james-jory — APPROVED** [review]

**Pull request merged**
