### PR TITLE
FenixCommerce -  Delivery Date+Shipping

### PR DESCRIPTION
**Pull request by ajayfenix**
This issue includes **FenixCommerce** Smart delivery dates on Product page, Category Page, Cart Page, Checkout Page. 

1. Integration uses 3rd Party API https://ipinfo.io/ to detect zipcode. 
2. Based on product ids and SKU we see product delivery dates estimates on different sections. 

Here are few sample screenshots the UI look. 

**Product Page :** 
screenshot-d13u6vjwmpf9g1 cloudfront net-2022 03 04-21_04_38

====================================================

**Category Page :**
screenshot-d13u6vjwmpf9g1 cloudfront net-2022 03 04-21_07_03

====================================================

**Cart Page :**

screenshot-d13u6vjwmpf9g1 cloudfront net-2022 03 04-21_08_09 (1)

====================================================

**Checkout Page:**

screenshot-d13u6vjwmpf9g1 cloudfront net-2022 03 04-21_09_46

====================================================

By submitting this pull request, I confirm that FenixCommerce can use, modify, copy, and redistribute this contribution, under the terms of your choice and review commits received to Fenix team.

### CODE REVIEW

**Comment by ronaks4** [comment]
I am working with Fenix commerce. I will review with Fenix team and update.

**Comment by ronaks4** [comment]
use this PR https://github.com/aws-samples/retail-demo-store/pull/346 and close / cancel this one.

**Comment by james-jory** [comment]
Sorry, I didn't see this PR when reviewing the invalid zip code PR. Please resolve conflicts in this PR when you get a chance. Thanks!

**Comment by ronaks4** [comment]
James, per previous comment, please close / cancel this PR. There were multiple issues with this PR and https://github.com/aws-samples/retail-demo-store/pull/346 is correct one which we already completed. Thank you, ronak

**Comment by BastLeblanc** [comment]
closing this one. #346 has been merged

**Pull request closed without merging**
