### PR TITLE
Fix timeouts indexing products and optimize loading

### PR DESCRIPTION
**Pull request by james-jory**
*Description of changes:*

Resolving some recurring issues with deployments.

- When pre-indexing in Elasticsearch is selected, the lambda would sometimes timeout when the ES server would need to merge segments or the JVM would GC. The client now has a longer timeout and will retry. This should make this lambda more reliable.
- The custom resource lambda that loaded products in DDB was loading them for all CFN event types. Now it only loads on "Create" event types.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by alexchirayath** [comment]
LGTM. Has this been tested on an instance?
Also, one callout here is that if  the product list is updated, the stack update does not have any logic to update the product list

**Review by alexchirayath — APPROVED** [review]

**Comment by james-jory** [comment]
> LGTM. Has this been tested on an instance?

Yes, it has been tested on a fresh deployment.

> Also, one callout here is that if the product list is updated, the stack update does not have any logic to update the product list

Yes. That is unrelated to these changes, though. My change to the product load lambda was really to prevent the lambda from trying to load the product and category DDB tables during a CFN "Delete" event. Besides being unnecessary, I was seeing some instability during CFN teardown so was making the logic more precise. Updating the products/categories YAML files in the staging bucket and updating the stack will not trigger an "Update" to the product load custom resource since those files are external to the CFN template. The custom resource itself would need to be updated to trigger the lambda to run with an "Update" event type. Nevertheless, I added the "Update" event to the conditional logic that loads the tables so it's there if we ever add something like a version template parameter that can be used to trigger the resource to update. With that said, you can still run the Lambda directly to update products from the YAML file (I've done this many times before).

**Review by manbearshark — COMMENTED** [review]
LGTM!

**Review by manbearshark — COMMENTED** [review]
Maybe the main.go fn could return an error when an unexpected query type is sent?

**Pull request merged**
