### PR TITLE
Update Lab-5-Real-time-events-Segment.ipynb

### PR DESCRIPTION
**Pull request by sjaffari**
*Issue #, if available:*

*Description of changes: Removed external ID instructions. Segment functionality has changed where a user cannot hard code an external ID. 

*Description of testing performed to validate your changes (required if pull request includes CloudFormation or source code changes): I successfully completed the workshop up to successfully sending data to Segment without entering External ID

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by james-jory — APPROVED** [review]
Thank you for the PR!

**Comment by james-jory** [comment]
@sjaffari, after further inspection, do the instructions need to updated (rather than removed) to instruct the user to update the `sts:ExternalId` value in the [SegmentCrossAccountLambdaExecutionRole](https://github.com/aws-samples/retail-demo-store/blob/a28e3a362ddf1d284ed6b9e510ee11e63c43fd6c/aws/cloudformation-templates/segment.yaml#L60) to match the value set by Segment?

**Comment by sjaffari** [comment]
@james-jory I suspected that as well but I just walked through the workshop and was able to send data to Segment without updating the external ID. 
B3CD29FB-7D6D-4831-A69B-5120B5F261D4

**Comment by james-jory** [comment]
@sjaffari, are you using the [SegmentCrossAccountLambdaExecutionRole](https://github.com/aws-samples/retail-demo-store/blob/a28e3a362ddf1d284ed6b9e510ee11e63c43fd6c/aws/cloudformation-templates/segment.yaml#L60) as the IAM Role in your Personalize destination config in Segment?

**Comment by sjaffari** [comment]
Hi James,

Yes I am.

[image: image.png]


Safdar Jaffari
Strategic Partner Engineer (Segment)
[image: %(logoAlt)s] <https://www.twilio.com/?utm_source=email_signature>
MOBILE
EMAIL ***@***.***

**Comment by sjaffari** [comment]
@james-jory  Yes we are. After consulting with Ajit, we can add verbiage instructing users to change the externalID on the role to match what is in Segment.

**Pull request merged**
